# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g8_-x4PbOOxMuPZDuWWXdA389frMKaVx
"""


import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Title
st.title("Digital Dosha Monitoring Dashboard")

# Upload or use a local file
uploaded_file = "R_V_P_K.xlsx"  # Change this if using st.file_uploader

# Read data
df = pd.read_excel(uploaded_file)

# Rename columns if needed
df.columns = ['Timing', 'Vatha', 'Pitha', 'Kapha']

# Show raw data
st.subheader("Raw Dosha Data")
st.dataframe(df)

# Line chart for doshas over time
st.subheader("Dosha Trends Over Time")
st.line_chart(df.set_index('Timing')[['Vatha', 'Pitha', 'Kapha']])

# Optional: Show statistics
st.subheader("Dosha Summary Statistics")
st.write(df.describe())
